
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action mmFile;
	private global::Gtk.Action Action;
	private global::Gtk.Action dialogQuestionAction;
	private global::Gtk.Action mmFileExit;
	private global::Gtk.Action mmFileOpen;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar main_menu;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.mmFile = new global::Gtk.Action ("mmFile", global::Mono.Unix.Catalog.GetString ("Файл"), null, null);
		this.mmFile.ShortLabel = global::Mono.Unix.Catalog.GetString ("Файл");
		w1.Add (this.mmFile, null);
		this.Action = new global::Gtk.Action ("Action", global::Mono.Unix.Catalog.GetString ("Помощь"), null, null);
		this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("Помощь");
		w1.Add (this.Action, null);
		this.dialogQuestionAction = new global::Gtk.Action ("dialogQuestionAction", global::Mono.Unix.Catalog.GetString ("О программе"), null, "gtk-dialog-question");
		this.dialogQuestionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("О программе");
		w1.Add (this.dialogQuestionAction, null);
		this.mmFileExit = new global::Gtk.Action ("mmFileExit", global::Mono.Unix.Catalog.GetString ("Выход"), null, "gtk-no");
		this.mmFileExit.ShortLabel = global::Mono.Unix.Catalog.GetString ("Выход");
		w1.Add (this.mmFileExit, null);
		this.mmFileOpen = new global::Gtk.Action ("mmFileOpen", global::Mono.Unix.Catalog.GetString ("Открыть"), null, null);
		this.mmFileOpen.ShortLabel = global::Mono.Unix.Catalog.GetString ("Открыть");
		w1.Add (this.mmFileOpen, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Мои Утилиты");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-authentication", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='main_menu'><menu name='mmFile' action='mmFile'><menuitem name='mmFileExit' action='mmFileExit'/></menu><menu name='Action' action='Action'><menuitem name='dialogQuestionAction' action='dialogQuestionAction'/></menu></menubar></ui>");
		this.main_menu = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/main_menu")));
		this.main_menu.Name = "main_menu";
		this.vbox1.Add (this.main_menu);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.main_menu]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 529;
		this.DefaultHeight = 344;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.dialogQuestionAction.Activated += new global::System.EventHandler (this.OnDialogQuestionActionActivated);
		this.mmFileExit.Activated += new global::System.EventHandler (this.OnMmFileExitActivated);
	}
}
