
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action bAction;
	
	private global::Gtk.Action colorPickerAction;
	
	private global::Gtk.Action deleteAction;
	
	private global::Gtk.Action aAction;
	
	private global::Gtk.Action vAction;
	
	private global::Gtk.Action cAction;
	
	private global::Gtk.Action aAction1;
	
	private global::Gtk.Action bAction1;
	
	private global::Gtk.Action bAction2;
	
	private global::Gtk.Action cAction1;
	
	private global::Gtk.Fixed fixed2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.bAction = new global::Gtk.Action ("bAction", global::Mono.Unix.Catalog.GetString ("b"), null, null);
		this.bAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("b");
		w1.Add (this.bAction, null);
		this.colorPickerAction = new global::Gtk.Action ("colorPickerAction", global::Mono.Unix.Catalog.GetString ("a"), null, "gtk-color-picker");
		this.colorPickerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("a");
		w1.Add (this.colorPickerAction, null);
		this.deleteAction = new global::Gtk.Action ("deleteAction", global::Mono.Unix.Catalog.GetString ("b"), null, "gtk-delete");
		this.deleteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("b");
		w1.Add (this.deleteAction, null);
		this.aAction = new global::Gtk.Action ("aAction", global::Mono.Unix.Catalog.GetString ("a"), null, null);
		this.aAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("a");
		w1.Add (this.aAction, null);
		this.vAction = new global::Gtk.Action ("vAction", global::Mono.Unix.Catalog.GetString ("v"), null, null);
		this.vAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("v");
		w1.Add (this.vAction, null);
		this.cAction = new global::Gtk.Action ("cAction", global::Mono.Unix.Catalog.GetString ("c"), null, null);
		this.cAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("c");
		w1.Add (this.cAction, null);
		this.aAction1 = new global::Gtk.Action ("aAction1", global::Mono.Unix.Catalog.GetString ("a"), null, null);
		this.aAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("a");
		w1.Add (this.aAction1, null);
		this.bAction1 = new global::Gtk.Action ("bAction1", global::Mono.Unix.Catalog.GetString ("b"), null, null);
		this.bAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("b");
		w1.Add (this.bAction1, null);
		this.bAction2 = new global::Gtk.Action ("bAction2", global::Mono.Unix.Catalog.GetString ("b"), null, null);
		this.bAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("b");
		w1.Add (this.bAction2, null);
		this.cAction1 = new global::Gtk.Action ("cAction1", global::Mono.Unix.Catalog.GetString ("c"), null, null);
		this.cAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("c");
		w1.Add (this.cAction1, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.Add (this.fixed2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 746;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
